// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACwtUFYmxysw2RMpD06jc3jNkCzmZj15M',
    appId: '1:459471336521:web:dc01e5c8d27b08be607b98',
    messagingSenderId: '459471336521',
    projectId: 'giuaki-db-dc848',
    authDomain: 'giuaki-db-dc848.firebaseapp.com',
    storageBucket: 'giuaki-db-dc848.appspot.com',
    measurementId: 'G-9WXZTQ2CYC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApUmwjk2iwEN4ak1OLWoxj-OfmoLHoJcE',
    appId: '1:459471336521:android:accb4308cf503e5f607b98',
    messagingSenderId: '459471336521',
    projectId: 'giuaki-db-dc848',
    storageBucket: 'giuaki-db-dc848.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAa1ccKJ_g48J7jPgP_JePxifW8h1_4Zcg',
    appId: '1:459471336521:ios:6ff4e7f754257823607b98',
    messagingSenderId: '459471336521',
    projectId: 'giuaki-db-dc848',
    storageBucket: 'giuaki-db-dc848.appspot.com',
    iosBundleId: 'com.example.baithigiuakiTgtd',
  );
}
